### ISSUE TITLE
Refresh ctop after kill a container

### ISSUE THREAD

**Issue by yesnault** [yadutaf/ctop#1]
Hi,

Run ctop
Start a container
ctop detect new container
Stop or kill container
ctop doesn't remove container
restart ctop
ctop does not display removed container

We have to restart ctop to not see removed container. Is-it the desired behaviour ?

**Comment by yadutaf** [comment]
Definitively not the intended behavior. I'll look into this ASAP. Thanks for reporting.

**Comment by yadutaf** [comment]
Turns out be an easy one. Fixed.
