### ISSUE TITLE
Permanent error "Cannot allocate memory"

### ISSUE THREAD

**Issue by mrqwer88** [yadutaf/ctop#12]
Hello!

This problem looks little strange.
On one hw node, start without interval and - 

```
./ctop --follow=/1212
Traceback (most recent call last):
  File "./ctop", line 903, in <module>
    main()
  File "./ctop", line 877, in main
    collect(measures)
  File "./ctop", line 349, in collect
    cur[cgroup.name]['blkio.throttle.io_service_bytes'] = cgroup['blkio.throttle.io_service_bytes']
  File "./ctop", line 246, in __getitem__
    content = f.read().strip()
IOError: [Errno 12] Cannot allocate memory

./ctop --follow=/1212
Traceback (most recent call last):
  File "./ctop", line 903, in <module>
    main()
  File "./ctop", line 877, in main
    collect(measures)
  File "./ctop", line 349, in collect
    cur[cgroup.name]['blkio.throttle.io_service_bytes'] = cgroup['blkio.throttle.io_service_bytes']
  File "./ctop", line 246, in __getitem__
    content = f.read().strip()
IOError: [Errno 12] Cannot allocate memory
```

And again without pause next two start ctop work good with this key and without it.
On hw node was availble ~10G free memroy and 100+G cached memory, when I run ctop.

**Comment by yadutaf** [comment]
Hi,

Thanks for reporting this problem. I do not have access to a system with comparable amount of memory but I'll try to help anyway. How many OpenVZ containers do you have on this host ? Does the number of containers appears to have an impact on this issue ? Do you still have the issue without "--follow" ? Is there any combination of options that would allow to mitigate this bug ? Is ctop itself running in a container / cgroup with local restrictions ?

Thanks,

**Comment by mrqwer88** [comment]
> How many OpenVZ containers do you have on this host ?

334

> Does the number of containers appears to have an impact on this issue ?

Not sure. How I remember I saw same error with 50+ containers on node.

> Do you still have the issue without "--follow" ? 
> Is there any combination of options that would allow to mitigate this bug 

It is improbable. With this flag with one group name it work good befor error and after error.

> Is ctop itself running in a container / cgroup with local restrictions ?

Ctop running from hw node from root user, when I have this error.

**Comment by yadutaf** [comment]
Unfortunately, I could not find a reliable way to reproduce and close this bug. I'll have to close the issue. Feel free to re-open if you have any new input. Thanks again for your feedback.
