### ISSUE TITLE
Filter by type

### ISSUE THREAD

**Issue by xkrt** [yadutaf/ctop#16]
Hi, it would be useful to apply a filter by container type. Real use case: show only docker containers and hide all systemd.

**Comment by yadutaf** [comment]
Can you test with branch https://github.com/yadutaf/ctop/tree/jt-filter-by-type ? Adds parameter `--type` which may be supplied multiple times. Supports both list and tree displays. In case of trees, it keeps the ancestry instead of blindly breaking the display.

**Comment by xkrt** [comment]
@yadutaf I did the test, all is works as expected, thanks!

**Comment by yadutaf** [comment]
Merged. Thanks for the feedback.
