### ISSUE TITLE
Trying to run

### ISSUE THREAD

**Issue by kurktchiev** [yadutaf/ctop#17]
I just tried to run ctop for the first time and upon execute i got this:
Traceback (most recent call last):
  File "/usr/bin/ctop", line 4, in <module>
    cgroup_top.main()
  File "/usr/lib/python2.7/site-packages/cgroup_top.py", line 782, in main
    curses.curs_set(0)   # hide cursor
_curses.error: curs_set() returned ERR

----> cat /proc/cgroups
# subsys_name    hierarchy   num_cgroups enabled

cpuset  6   36  1
cpu 2   161 1
cpuacct 2   161 1
memory  4   161 1
devices 7   36  1
freezer 5   36  1
net_cls 8   36  1
blkio   9   161 1
perf_event  3   3   1
hugetlb 10  36  1

----> mount | grep group
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,seclabel,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)

Not sure where to go from here

**Comment by yadutaf** [comment]
Curses and terminals weirdness. Sights... At least the open source community is full of similar reports... I'll go for https://github.com/zalando/pg_view/commit/cef4bbbc4d91cc14ebb134c1a5e4748b31f1f0a9

**Comment by yadutaf** [comment]
Fixed. Can you confirm it works before I merge to master ? Thanks for the report !

**Comment by kurktchiev** [comment]
Yes that seems to have done the trick.

**Comment by yadutaf** [comment]
Thanks for your feedback!
