### ISSUE TITLE
exit shell / console

### ISSUE THREAD

**Issue by pingmurder** [yadutaf/ctop#22]
When using ctop to access a containers console or shell, exit from that shell returns back to the console login. Ctrl c, q etc do nothing at this point and the shell session has to be terminated

Need an exit method that returns back to ctop screen

**Comment by yadutaf** [comment]
Hi @pingmurder 

Unless something is broken, you should return to ctop screen as soon as the container shell or console exist. It it run as a sub command by design.

What do you mean by "console login" ? Could you provide screenshots ?

**Comment by pingmurder** [comment]
In cTop select a container and hit key to go to console or shell
at console or shell login, input incorrect login  - there's no way to exit from here other than terminating the entire shell.

You either have to get into console / shell or terminate your session.

**Comment by yadutaf** [comment]
Thanks for the precisions. What kind of containers do you use (Docker/LXC/OpenVZ/...)?

**Comment by pingmurder** [comment]
This is for an Openvz based system

**Comment by yadutaf** [comment]
Interesting. Could you submit a PR ? I don't have access to OpenVZ host to implement this feature. OpenVZ support was contributed by the community.

**Comment by mrqwer88** [comment]
What version OpenVZ you use? Are you use correct ways to exit from container?
Check it on OpenVZ 6 (Centos 6, vzctl version 4.9.4).
After "A" - attach(vzctl console) it correct exit from container and return to ctop by `ESC` + `.`
After "E" - enter(vzctl enter) it correct exit from container and return to ctop by `CTRL`+`D`

**Comment by yadutaf** [comment]
@mrqwer88 awesome informations! Maybe we should add them to the README?

**Comment by yadutaf** [comment]
Closing as inactive. Feel free to re-open if you have any further comment.
