### ISSUE TITLE
Initial runtime error

### ISSUE THREAD

**Issue by rwstauner** [yadutaf/ctop#3]
I installed via pip, tried to run `ctop` and got the following error:

```
Traceback (most recent call last):
  File "/home/rando/python/venv/2.7.3/bin/ctop", line 4, in <module>
    cgroup_top.main()
  File "/home/rando/python/venv/2.7.3/local/lib/python2.7/site-packages/cgroup_top.py", line 746, in main
    display(stdscr, results, CONFIGURATION)
  File "/home/rando/python/venv/2.7.3/local/lib/python2.7/site-packages/cgroup_top.py", line 432, in display
    CONFIGURATION['selected_line_name'] = CONFIGURATION['cgroups'][CONFIGURATION['selected_line_num']]
IndexError: list index out of range
```

Is there something i'm supposed to do first?
Is this a limitation of my system?  I'm on ubuntu 12.04.
I usually run docker via boot2docker b/c I know my kernel is old... does ctop require something I don't have?

**Comment by yadutaf** [comment]
This crash is definitively a bug. It should at least print a friendlier error message. My guess is that `ctop` did not find any cgroups. 

Can you paste here the output of `mount | grep group` and `cat /proc/cgroups` ?

If you're planning on monitoring Docker containers inside boot2docker, you need to run ctop in the VM itself. I suggest you try the Dockerized version. It may be closer to your needs.

Thanks for the report,

**Comment by rwstauner** [comment]
Makes sense (that it would need to run from the docker host), but since i didn't know what it was supposed to do (and obviously got an error message) I thought i'd share my experience.
I wasn't sure if there was a way to communicate with the vm from my host (like docker does (via boot2docker's env vars)) or not.

```
💥  mount | grep group
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)

💥  cat /proc/cgroups
#subsys_name    hierarchy       num_cgroups     enabled
cpuset  1       1       1
cpu     2       1       1
cpuacct 3       1       1
memory  4       1       1
devices 5       1       1
freezer 6       1       1
blkio   7       1       1
perf_event      8       1       1
```

**Comment by yadutaf** [comment]
Thanks! These were run in the docker host right? Does the Dockerized approach works for you?

If so, I will:
- Document the boot2docker use case in the README.
- Print a helpful error message in place of the weird stack trace when running from the main host.

Does it look good to you?

**Comment by rwstauner** [comment]
Actually this was run from my host machine.
When I use docker, I typically use it with boot2docker, however, there is usually a docker daemon running on my host (if i kill it, it just comes back).  I assume it has something to do with the way it was installed.

I noticed today that I didn't previously have permission for the docker socket on my host (the one I don't use), so I get an error trying `docker ps`.  I fixed my permissions, and now `docker ps` shows me a list of "no containers" which is accurate, however I get the same output from `ctop`.
So I guess that doesn't help much.

I do apologize for the confusion, I'm sure I'm not doing things "normally".
I'm glad to help debug, though.

**Comment by yadutaf** [comment]
Can you retry from master and confirm this is fixed for you ? #4 changes the default highlighted line while 8d8a0b371adcd0de10d3ba543b41380f801fc236 should display a better help message when no local cgroup is found and boot2docker is installed.

**Comment by rwstauner** [comment]
Now ctop runs, showing the header and one row:

```
OWNER      TYPE       PROC      MEMORY       SYST  USER    BLKIO        TIME+      CGROUP
root       -          1261   6.2GB/11.7GB     0.0% 12.8%    0.0 B/s  198d 10:39.43 /
```

Upon quitting, it shows me the boot2docker message.

```
[WARN] Failed to find any relevant cgroup/container.ree view x [Q]uit

Hint: It seems you have 'boot2docker' installed.
      To monitor Docker containers in 'boot2docker'
      run CTOP inside the VM itself with:
      $ docker run --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro -it --rm yadutaf/ctop
```

However, if I try the docker command suggested, I get a new error:

```
💥  docker run --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro -it --rm yadutaf/ctop
Traceback (most recent call last):
  File "/usr/local/bin/ctop", line 4, in <module>
    __import__('pkg_resources').run_script('ctop==0.4.0', 'ctop')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1649, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/ctop-0.4.0-py2.7.egg/EGG-INFO/scripts/ctop", line 4, in <module>
    __import__('pkg_resources').run_script('ctop==0.4.0', 'ctop')
  File "build/bdist.linux-x86_64/egg/cgroup_top.py", line 785, in main
  File "build/bdist.linux-x86_64/egg/cgroup_top.py", line 327, in collect
  File "build/bdist.linux-x86_64/egg/cgroup_top.py", line 234, in __getitem__
IOError: [Errno 2] No such file or directory: '/sys/fs/cgroup/blkio/blkio.throttle.io_service_bytes'
```

**Comment by yadutaf** [comment]
OK, so first bug seems fixed. Let's move to the new one. Thanks.

**Comment by yadutaf** [comment]
I could not reproduce this bug. As the original bug is resolved, I'll marked this issue as resolved. If you still run into the second issue, feel free to open a new issue. Thanks.
