### ISSUE TITLE
IndexError when specifying type and no container of that type exists

### ISSUE THREAD

**Issue by akkerman** [yadutaf/ctop#43]
When starting ctop with a type and no container of that type exists, ctop doesn't start and prints a trace.

When there _are_ containers of that type ctop starts normally. 
However when, at some time, all containers of that type are removed ctop will halt with the same trace.

```
$ ctop --type=docker
Traceback (most recent call last):
  File "/usr/local/bin/ctop", line 4, in <module>
    cgroup_top.main()
  File "/usr/local/lib/python2.7/dist-packages/cgroup_top.py", line 1019, in main
    display(stdscr, results, CONFIGURATION)
  File "/usr/local/lib/python2.7/dist-packages/cgroup_top.py", line 619, in display
    CONFIGURATION['selected_line_name'] = CONFIGURATION['cgroups'][CONFIGURATION['selected_line_num']]
IndexError: list index out of range
```

Python: 2.7.6
Docker: 1.13.1
Ubuntu: 14.04.5 LTS

**Comment by yadutaf** [comment]
Thanks for the report. I'm just coming back from a couple of days off. According to the stack trace, ctop does not like when it does not find any container. Let's fix this.

**Comment by yadutaf** [comment]
Fixed.

**Comment by akkerman** [comment]
tested
works just like you expect
thanks
