### ISSUE TITLE
No visible docker container on Jessie

### ISSUE THREAD

**Issue by NicolasLM** [yadutaf/ctop#5]
Not sure if it's a bug but here is the behavior I get
- Boot the host on Debian Jessie (using systemd).
- Run ctop. No cgroup visible, just `/`.
- Launch a docker container.
- Check ctop. Two main groups appeared, all related to systemd (system.slice and user.slice) but nothing about the docker container.

**Comment by yadutaf** [comment]
Thanks for reporting! I'll have a look this week.

**Comment by yadutaf** [comment]
That's weird. On boot, all cgroups are empty, except `/systemd` which is currently not monitored by ctop. But, as soon as a Docker container is started, I get the full cgroup tree. I'm afraid this is a systemd or system configuration issue, not a ctop bug.
