### ISSUE TITLE
Limit for max count containers on hw node

### ISSUE THREAD

**Issue by mrqwer88** [yadutaf/ctop#9]
Hello.

Are ctop have limit for max cout containers on node?
About 60 containers on node?

If I run ctop on node with 55 containers - it work good.

If I run ctop on node with 60 containers or more - it failed with error 

```
./ctop 
Traceback (most recent call last):
  File "./ctop", line 836, in <module>
    main()
  File "./ctop", line 811, in main
    results = built_statistics(measures, CONFIGURATION)
  File "./ctop", line 360, in built_statistics
    'tasks': len(data['tasks']),
KeyError: 'tasks'

```

I run it on OpenVZ nodes, if  this is important.
PS And terminal size  211x56 symbols.
My height in 56 is limit for me now?

**Comment by mrqwer88** [comment]
> And terminal size 211x56 symbols.
> My height in 56 is limit for me now?

No,  it is not related. I resize it to 37 on height, but ctop with 55 containers work good, yet.

**Comment by yadutaf** [comment]
It looks like ctop failed to collect task list for one of the containers. I'll add a `--debug` flag to print the last collected samples on exit. I'll need this to do a proper fix.

**Comment by mrqwer88** [comment]
Yes - you wrigth.
I have same error when set incorrect name in ctid in 

```
cur[ctid]['memory.usage_in_bytes'] = privvmpages
```

Wait version with --debug flag.

**Comment by yadutaf** [comment]
Reproduced + fixed. Thanks for reporting.
